### ISSUE TITLE
[P2] Missing cards after deck import

### ISSUE THREAD

**Issue by Shadowinter** [open-duelyst/duelyst#262] opened 2023-01-15 03:21 UTC
## Summary

when i try to import a deck it says deck imported but missing cards

## Impacted services

- [ ] The frontend app
- [ ] Duelyst
- [ ] Game builds or automation scripts

- Operating system: Windows
- Browser: Chrome
- Browser version: lastest

## Additional context

![duelist bug](https://user-images.githubusercontent.com/122637523/212521292-db591c1f-3aa3-431d-91e8-66fdb9f07788.png)

**Comment by willroberts** [comment] 2023-01-15 04:15
Hi, can you share the JSON for the export so we can attempt to reproduce the issue?

**Comment by willroberts** [comment] 2023-01-15 14:51
Can you also try importing a deck while not currently editing a deck?

**Comment by Shadowinter** [comment] 2023-01-16 02:27
> Hi, can you share the JSON for the export so we can attempt to reproduce the issue?
 here we go
[vetruvian starter]MToyNjQsMjoyNjUsMzoyNjYsMzoyNjksMzoyNzEsMzoyNzIsMzoxMTE2NSwzOjExMTkzLDI6MTEyMTMsMjoyMDQ0MCwyOjIwNDQyLDE6MjA0NDMsMjoyMDQ0NSwzOjIwNDQ4LDI6MjA0NDksMjoyMDQ1NCwzOjMwMTA3                                                                                                                               

> Can you also try importing a deck while not currently editing a deck?

i tryed don't work the message "failed to export a deck"

**Comment by yoganlava** [comment] 2023-01-16 19:14
Pretty sure this is a Duelyst 2 deck?

**Comment by willroberts** [comment] 2023-01-17 16:56
Yes, it's also base64-encoded instead of being plain JSON (which is what OpenDuelyst expects). Decoding reveals this (also not JSON):

```
1:568,2:572,1:574,2:576,2:578,2:579,1:580,3:585,1:592,1:11228,2:11237,3:11251,3:20491,2:20492,3:20493,3:20494,2:20495,1:20497,2:20505,2:20507,1:30116
```

Will close this since OpenDuelyst doesn't support Duelyst 2 import/export formats or cards.

**Closed by willroberts** 2023-01-17 16:56 UTC
Labels: bug
