### ISSUE TITLE
it does not run: Looks like your video card is not supported.

### ISSUE THREAD

**Issue by mdtrooper** [open-duelyst/duelyst#253] opened 2023-01-12 12:49 UTC
## Summary

Launch the game, it shows the loading screen and ends with next black screen:

![imagen](https://user-images.githubusercontent.com/1285451/212068664-b0e7f421-0833-4728-b587-92f7a07c514c.png)

And it does not show any log.

## Impacted services

- [x] The frontend app
- [ ] The game servers
- [ ] Game builds or automation scripts
- [ ] Tests or Github Actions
- [ ] Infrastructure (Terraform)

## Steps to reproduce

1. ... Launch the game.
2. ...
3. ...

## Environment information

- Operating system: Linux
- Browser: 
- Browser version: 

## Additional context

- Version:  duelyst-desktop-v1.97.10-linux-x64.zip 

```$ lsb_release --all
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21
Release:	21
Codename:	vanessa
```
```
$ uname -a
Linux portatil 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ lshw
portatil
    description: Computer
    width: 64 bits
    capabilities: smp vsyscall32
  *-core
       description: Motherboard
       physical id: 0
     *-memory
          description: System memory
          physical id: 0
          size: 23GiB
     *-cpu
          product: AMD Ryzen 5 5500U with Radeon Graphics
          vendor: Advanced Micro Devices [AMD]
          physical id: 1
          bus info: cpu@0
          version: 23.104.1
          size: 3190MHz
          capacity: 4056MHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp x86-64 constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca cpufreq
          configuration: microcode=140542211
     *-pci:0
          description: Host bridge
          product: Renoir/Cezanne Root Complex
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 00
          width: 32 bits
          clock: 33MHz
        *-generic UNCLAIMED
             description: IOMMU
             product: Renoir/Cezanne IOMMU
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 0.2
             bus info: pci@0000:00:00.2
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: cap_list
             configuration: latency=0
        *-pci:0
             description: PCI bridge
             product: Renoir/Cezanne PCIe GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 2.1
             bus info: pci@0000:00:02.1
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:26 ioport:4000(size=4096) memory:fd500000-fd5fffff ioport:630000000(size=2097152)
           *-nvme
                description: NVMe device
                product: SKHynix_HFM256GD3HX015N
                vendor: SK hynix
                physical id: 0
                bus info: pci@0000:01:00.0
                logical name: /dev/nvme0
                version: 41040C20
                serial: CYB5N01271CA05E4Z
                width: 64 bits
                clock: 33MHz
                capabilities: nvme nvm_express bus_master cap_list
                configuration: driver=nvme latency=0 nqn=nqn.2022-05.com.skhynix:nvme:nvm-subsystem-sn-CYB5N01271CA05E4Z state=live
                resources: irq:40 memory:fd500000-fd503fff memory:fd505000-fd505fff memory:fd504000-fd504fff
              *-namespace:0
                   description: NVMe disk
                   physical id: 0
                   logical name: hwmon2
              *-namespace:1
                   description: NVMe disk
                   physical id: 2
                   logical name: /dev/ng0n1
              *-namespace:2
                   description: NVMe disk
                   physical id: 1
                   bus info: nvme@0:1
                   logical name: /dev/nvme0n1
                   configuration: wwid=eui.ace42e002a6dcf0e2ee4ac0000000001
        *-pci:1
             description: PCI bridge
             product: Renoir/Cezanne PCIe GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 2.2
             bus info: pci@0000:00:02.2
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:27 ioport:2000(size=4096) memory:fd400000-fd4fffff ioport:630200000(size=2097152)
           *-network
                description: Ethernet interface
                product: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
                vendor: Realtek Semiconductor Co., Ltd.
                physical id: 0
                bus info: pci@0000:02:00.0
                logical name: enp2s0
                version: 10
                serial: 6c:24:08:9d:e5:ec
                size: 100Mbit/s
                capacity: 1Gbit/s
                width: 64 bits
                clock: 33MHz
                capabilities: bus_master cap_list ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
                configuration: autonegotiation=on broadcast=yes driver=r8169 driverversion=5.15.0-57-generic duplex=full firmware=rtl8168g-3_0.0.1 04/23/13 ip=192.168.1.34 latency=0 link=yes multicast=yes port=twisted pair speed=100Mbit/s
                resources: irq:39 ioport:2000(size=256) memory:fd404000-fd404fff memory:fd400000-fd403fff
        *-pci:2
             description: PCI bridge
             product: Renoir/Cezanne PCIe GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 2.3
             bus info: pci@0000:00:02.3
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:28 ioport:3000(size=4096) memory:d0000000-d01fffff ioport:670200000(size=2097152)
           *-network DISABLED
                description: Wireless interface
                product: MT7921 802.11ax PCI Express Wireless Network Adapter
                vendor: MEDIATEK Corp.
                physical id: 0
                bus info: pci@0000:03:00.0
                logical name: wlp3s0
                version: 00
                serial: 30:03:c8:b8:16:7d
                width: 64 bits
                clock: 33MHz
                capabilities: bus_master cap_list ethernet physical wireless
                configuration: broadcast=yes driver=mt7921e driverversion=5.15.0-57-generic firmware=____010000-20220209150915 latency=0 link=no multicast=yes wireless=IEEE 802.11
                resources: iomemory:60-5f iomemory:60-5f iomemory:60-5f irq:75 memory:670200000-6702fffff memory:670300000-670303fff memory:670304000-670304fff
        *-pci:3
             description: PCI bridge
             product: Renoir Internal PCIe GPP Bridge to Bus
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 8.1
             bus info: pci@0000:00:08.1
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:29 ioport:1000(size=4096) memory:fd000000-fd3fffff ioport:660000000(size=270532608)
           *-display
                description: VGA compatible controller
                product: Lucienne
                vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                physical id: 0
                bus info: pci@0000:04:00.0
                logical name: /dev/fb0
                version: c2
                width: 64 bits
                clock: 33MHz
                capabilities: vga_controller bus_master cap_list fb
                configuration: depth=32 driver=amdgpu latency=0 resolution=1920,1080
                resources: iomemory:60-5f iomemory:60-5f irq:42 memory:660000000-66fffffff memory:670000000-6701fffff ioport:1000(size=256) memory:fd300000-fd37ffff
           *-multimedia:0
                description: Audio device
                product: Renoir Radeon High Definition Audio Controller
                vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                physical id: 0.1
                bus info: pci@0000:04:00.1
                logical name: card0
                logical name: /dev/snd/controlC0
                logical name: /dev/snd/hwC0D0
                logical name: /dev/snd/pcmC0D3p
                logical name: /dev/snd/pcmC0D7p
                logical name: /dev/snd/pcmC0D8p
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:73 memory:fd3c8000-fd3cbfff
              *-input:0
                   product: HD-Audio Generic HDMI/DP,pcm=3
                   physical id: 0
                   logical name: input12
                   logical name: /dev/input/event11
              *-input:1
                   product: HD-Audio Generic HDMI/DP,pcm=7
                   physical id: 1
                   logical name: input13
                   logical name: /dev/input/event12
              *-input:2
                   product: HD-Audio Generic HDMI/DP,pcm=8
                   physical id: 2
                   logical name: input14
                   logical name: /dev/input/event13
           *-generic
                description: Encryption controller
                product: Family 17h (Models 10h-1fh) Platform Security Processor
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.2
                bus info: pci@0000:04:00.2
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: bus_master cap_list
                configuration: driver=ccp latency=0
                resources: irq:40 memory:fd200000-fd2fffff memory:fd3cc000-fd3cdfff
           *-usb:0
                description: USB controller
                product: Renoir/Cezanne USB 3.1
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.3
                bus info: pci@0000:04:00.3
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: xhci bus_master cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:30 memory:fd000000-fd0fffff
           *-usb:1
                description: USB controller
                product: Renoir/Cezanne USB 3.1
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.4
                bus info: pci@0000:04:00.4
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: xhci bus_master cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:42 memory:fd100000-fd1fffff
           *-multimedia:1 UNCLAIMED
                description: Multimedia controller
                product: Raven/Raven2/FireFlight/Renoir Audio Processor
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.5
                bus info: pci@0000:04:00.5
                version: 01
                width: 32 bits
                clock: 33MHz
                capabilities: cap_list
                configuration: latency=0
                resources: memory:fd380000-fd3bffff
           *-multimedia:2
                description: Audio device
                product: Family 17h (Models 10h-1fh) HD Audio Controller
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.6
                bus info: pci@0000:04:00.6
                logical name: card1
                logical name: /dev/snd/controlC1
                logical name: /dev/snd/hwC1D0
                logical name: /dev/snd/pcmC1D0c
                logical name: /dev/snd/pcmC1D0p
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:41 memory:fd3c0000-fd3c7fff
              *-input:0
                   product: HD-Audio Generic Mic
                   physical id: 0
                   logical name: input16
                   logical name: /dev/input/event15
              *-input:1
                   product: HD-Audio Generic Headphone
                   physical id: 1
                   logical name: input17
                   logical name: /dev/input/event16
        *-serial
             description: SMBus
             product: FCH SMBus Controller
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 14
             bus info: pci@0000:00:14.0
             version: 51
             width: 32 bits
             clock: 66MHz
             configuration: driver=piix4_smbus latency=0
             resources: irq:0
        *-isa
             description: ISA bridge
             product: FCH LPC Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 14.3
             bus info: pci@0000:00:14.3
             version: 51
             width: 32 bits
             clock: 66MHz
             capabilities: isa bus_master
             configuration: latency=0
           *-pnp00:00
                product: PnP device PNP0c02
                physical id: 0
                capabilities: pnp
                configuration: driver=system
           *-pnp00:01
                product: PnP device PNP0b00
                physical id: 1
                capabilities: pnp
                configuration: driver=rtc_cmos
           *-pnp00:02
                product: PnP device PNP0c02
                physical id: 2
                capabilities: pnp
                configuration: driver=system
           *-pnp00:03
                product: PnP device PNP0c01
                physical id: 3
                capabilities: pnp
                configuration: driver=system
           *-pnp00:04
                product: PnP device LEN0071
                vendor: Lenovo Group Limited
                physical id: 4
                capabilities: pnp
                configuration: driver=i8042 kbd
           *-pnp00:05
                product: PnP device LEN2148
                vendor: Lenovo Group Limited
                physical id: 5
                capabilities: pnp
                configuration: driver=i8042 aux
     *-pci:1
          description: Host bridge
          product: Renoir PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 101
          bus info: pci@0000:00:01.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:2
          description: Host bridge
          product: Renoir PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 102
          bus info: pci@0000:00:02.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:3
          description: Host bridge
          product: Renoir PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 103
          bus info: pci@0000:00:08.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:4
          description: Host bridge
          product: Renoir Device 24: Function 0
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 104
          bus info: pci@0000:00:18.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:5
          description: Host bridge
          product: Renoir Device 24: Function 1
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 105
          bus info: pci@0000:00:18.1
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:6
          description: Host bridge
          product: Renoir Device 24: Function 2
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 106
          bus info: pci@0000:00:18.2
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:7
          description: Host bridge
          product: Renoir Device 24: Function 3
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 107
          bus info: pci@0000:00:18.3
          version: 00
          width: 32 bits
          clock: 33MHz
          configuration: driver=k10temp
          resources: irq:0
     *-pci:8
          description: Host bridge
          product: Renoir Device 24: Function 4
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 108
          bus info: pci@0000:00:18.4
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:9
          description: Host bridge
          product: Renoir Device 24: Function 5
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 109
          bus info: pci@0000:00:18.5
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:10
          description: Host bridge
          product: Renoir Device 24: Function 6
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10a
          bus info: pci@0000:00:18.6
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:11
          description: Host bridge
          product: Renoir Device 24: Function 7
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10b
          bus info: pci@0000:00:18.7
          version: 00
          width: 32 bits
          clock: 33MHz
  *-input:0
       product: Power Button
       physical id: 1
       logical name: input0
       logical name: /dev/input/event0
       capabilities: platform
  *-input:1
       product: Lid Switch
       physical id: 2
       logical name: input1
       logical name: /dev/input/event1
       capabilities: platform
  *-input:2
       product: ThinkPad Extra Buttons
       physical id: 3
       logical name: input11
       logical name: /dev/input/event10
       capabilities: platform
  *-input:3
       product: Integrated Camera: Integrated C
       physical id: 4
       logical name: input15
       logical name: /dev/input/event14
       capabilities: usb
  *-input:4
       product: Sleep Button
       physical id: 5
       logical name: input2
       logical name: /dev/input/event2
       capabilities: platform
  *-input:5
       product: DELL Dell QuietKey Keyboard
       physical id: 6
       logical name: input21
       logical name: /dev/input/event9
       logical name: input21::capslock
       logical name: input21::numlock
       logical name: input21::scrolllock
       capabilities: usb
  *-input:6
       product: Logitech USB Optical Mouse
       physical id: 7
       logical name: input25
       logical name: /dev/input/event8
       logical name: /dev/input/mouse2
       capabilities: usb
  *-input:7
       product: Power Button
       physical id: 8
       logical name: input3
       logical name: /dev/input/event3
       capabilities: platform
  *-input:8
       product: AT Translated Set 2 keyboard
       physical id: 9
       logical name: input4
       logical name: /dev/input/event4
       logical name: input4::capslock
       logical name: input4::numlock
       logical name: input4::scrolllock
       capabilities: i8042
  *-input:9
       product: ETPS/2 Elantech Touchpad
       physical id: a
       logical name: input6
       logical name: /dev/input/event7
       logical name: /dev/input/mouse1
       capabilities: i8042
  *-input:10
       product: Video Bus
       physical id: b
       logical name: input7
       logical name: /dev/input/event5
       capabilities: platform
  *-input:11
       product: ETPS/2 Elantech TrackPoint
       physical id: c
       logical name: input8
       logical name: /dev/input/event6
       logical name: /dev/input/mouse0
       capabilities: i8042
```

**Comment by willroberts** [comment] 2023-01-12 15:47
Hi @mdtrooper, does it work if you add these flags? https://github.com/open-duelyst/duelyst/issues/248#issuecomment-1378953785

**Comment by mdtrooper** [comment] 2023-01-12 16:33
> Hi @mdtrooper, does it work if you add these flags? [#248 (comment)](https://github.com/open-duelyst/duelyst/issues/248#issuecomment-1378953785)

Yes, now it runs fine.

But the game has not any help or other thing to show the flags:

```
$ ./Duelyst --help
$
```

**Comment by willroberts** [comment] 2023-01-12 20:59
Great! I'll close this issue as a duplicate of #248. We're planning to incorporate these flags into the build so they don't need to be passed in.

Regarding a `--help` flag, we currently don't have one. The desktop app is an Electron app, which has its own [internal flags system](https://www.electronjs.org/docs/latest/api/command-line-switches), but perhaps that can be extended to add additional flags.

**Closed** 2023-01-12 20:59 UTC
Labels: bug
